# Generated by Django 6.0.2 on 2026-02-20 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traducao',
            name='idioma_destino',
            field=models.CharField(default='português', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traducao',
            name='idioma_origem',
            field=models.CharField(default='portugues', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='traducao',
            name='idioma_kiriri',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='traducao',
            name='idioma_portugues',
            field=models.TextField(),
        ),
    ]
