# Generated by Django 6.0.2 on 2026-09-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_traducao_idioma_destino_traducao_idioma_origem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traducao',
            name='atualizacao_escrita',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traducao',
            name='interp_fonetica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traducao',
            name='kiriri_antigo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traducao',
            name='referencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='traducao',
            name='sentido',
            field=models.TextField(blank=True),
        ),
    ]
