# Generated by Django 6.0.2 on 2026-09-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_traducao_atualizacao_escrita_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traducao',
            name='idioma_destino',
        ),
        migrations.RemoveField(
            model_name='traducao',
            name='idioma_kiriri',
        ),
        migrations.RemoveField(
            model_name='traducao',
            name='idioma_origem',
        ),
        migrations.RemoveField(
            model_name='traducao',
            name='idioma_portugues',
        ),
        migrations.RemoveField(
            model_name='traducao',
            name='texto_original',
        ),
        migrations.RemoveField(
            model_name='traducao',
            name='texto_traduzido',
        ),
    ]
